### ISSUE TITLE
Incorrect type for Return Point Waveform Location

### ISSUE THREAD

**Issue by ghost** [mparkan/Digital-Forestry-Toolbox#11]
Hey @mparkan,
Thanks for fixing those other issues! Found another issue with LASWrite -the Return Point Waveform Location is being written as an incorrect type, currently is uint32, but should be a floating point single - same as the parametric dX/dY/dZ's.

Changing lines 1642-1643 from

`r.record(k).type = {'uint32', 'uint32', 'uint32', 'uint32'};`
`r.record(k).storage_type = {'uint32', 'uint32', 'uint32', 'uint32'};`

to 

`r.record(k).type = {'single', 'single', 'single', 'single'};`
`r.record(k).storage_type = {'single', 'single', 'single', 'single'};`

solves this issue for me.

Cheers.

**Comment by mparkan** [comment]
Thanks for reporting the issue.
