### ISSUE TITLE
Extended fields wrongly read

### ISSUE THREAD

**Issue by Jordi-Gene-Mola** [mparkan/Digital-Forestry-Toolbox#14]
Thank you very much for sharing this useful toolbox.

I am using the LASread.m script to read the following point cloud: [point_cloud_to_test_LASread.zip](https://github.com/mparkan/Digital-Forestry-Toolbox/files/6617828/point_cloud_to_test_LASread.zip). The code read all fields correctly unless the extended fields. For instance, opening the point cloud with CloudCompare the “Range” field have values from 0.85 m to 5 m. However, the “Range” values read with the LASread.m script ranges from 4.6059e+18 to 4.6173e+18. The same happen with other extended fields: “FrameIndex” and “Azimuth”. 
Do you have any idea how can I fix this issue?

Thank you in advance.
Best regards,
Jordi

**Comment by mparkan** [comment]
Thanks for reporting the issue. I've just updated LASread and it seems like it's reading the extra byte fields (azimuth, range, frame index) correctly now. Could you please let me know if it works as expected with your data?

**Comment by Jordi-Gene-Mola** [comment]
Great, it works! :)

Thank you very much for fixing this issue and for sharing this useful code :)

Jordi
