### ISSUE TITLE
saving a new las file by just using xyz or xyzRGB point data

### ISSUE THREAD

**Issue by songtaowhu** [mparkan/Digital-Forestry-Toolbox#4]
Thank you very much. It is very useful.
I have the difficulity in saving the new las file after merging multiple point cloud data (las files).
Can we save a new las file by just using the data in the form of xyz or xyzRGB?

**Comment by mparkan** [comment]
Hello, could you please be more specific about the issue with saving the merged point cloud and provided a description of the files you are trying to merge?

The LAS format has different versions (from 1.0 to 1.4) and supports various point data record formats. You can check the specifications here:

- [ASPRS - LASER (LAS) FILE FORMAT EXCHANGE ACTIVITIES](https://www.asprs.org/divisions-committees/lidar-division/laser-las-file-format-exchange-activities)

There is no LAS point data record format that contains only XYZRGB.

If you just need to save the xyz and RGB attributes, you could extract them from your LAS files (with _LASread_ function), merge them into a single xyzrgb Matlab/Octave variable and save the data as a Matlab/Octave binary file (with the _save_ function) or as CSV file (with the _fprintf_ function).

**Comment by deryagulcinubc** [comment]
Hi. I am doing Tutorial 2. But it gives me this error:

Expected one output from a curly brace or dot indexing expression, but there were 12267 results.

Error in treeMetrics (line 1276)
                   metrics.ConcaveHull3D{k,1} = nan;

Error in dft_tutorial_2 (line 191)
metrics_3d = treeMetrics(label_3d, ...
