### ISSUE TITLE
error reading LAS file

### ISSUE THREAD

**Issue by ericINRAE** [mparkan/Digital-Forestry-Toolbox#7]
Hi,
When reading a LAS file containing an extra scalar field, of type unsigned char (type 1), using the function LASread, I got the error message:
"Error using zeros
CLASSNAME input must be a valid numeric or logical class name."

In the file LASread.m, I had to replace line 1645:
r.extra_bytes(k).type = 'uchar'
by
r.extra_bytes(k).type = 'uint8';

as the string 'uchar' is not recognized by the Matlab function zeros.

**Comment by mparkan** [comment]
Hi, thanks for reporting the issue and sorry for the slow response. It should work as expected now.
