### ISSUE TITLE
LASWrite requires Statistics and Machine Learning Toolbox

### ISSUE THREAD

**Issue by ghost** [mparkan/Digital-Forestry-Toolbox#8]
When running LASWrite.m, it throws an error on line 2116 if the Statistics and Machine Learning is not installed.

Add a check for that toolbox and if it doesn't exist, use an alternate method to determine the equal lengths of the point data records:

```
if license('test','statistics_toolbox')
    if ~(range(n_records_per_attribute) == 0)
        error('LASwrite:unequalRecordLengths', 'The lengths of point data records are unequal');
    end
else
    if ~(max(n_records_per_attribute)-min(n_records_per_attribute) == 0)
        error('LASwrite:unequalRecordLengths', 'The lengths of point data records are unequal');
    end
end
```

**Comment by mparkan** [comment]
Thanks for reporting. I removed the dependency to the "Statistics and Machine Learning" toolbox.
